### PR TITLE
CodeRegistration & MetadataRegistration Offsets

### PR DESCRIPTION
**Pull request by Ekey**
Hey khang06. Can you tell me how to find these offsets (maybe you have some patterns for that)?

**1.4**
```
var codeRegistration = baseaddr + 0x72A0810;
var metadataRegistration = baseaddr + 0x7FBF040;
```

**1.5-dev**
```
var codeRegistration = baseaddr + 0xCC371E0;
var metadataRegistration = baseaddr + 0xF4EF330;
```

I would be grateful for any help. Best regards! 👍

### CODE REVIEW

**Comment by khang06** [comment]
it's been a while, so i forgot the exact method. sorry. my suggestion is to search for memory areas around the relevant stuff like the actual codeRegistration and metadataRegistration addresses
ida64_9VfR7l3rJH

in case you don't have 1.4's UserAssembly, you can download that [here](https://files.catbox.moe/1dhdg7.7z)

**Comment by Ekey** [comment]
Oh, awesome! I'll look it when I have free time! Thanks you so much! 👍

**Comment by Ekey** [comment]
Okay, if anyone is interested here fixes for 2.0. 

**Replace code in Program.cs**

```
var codeRegistration = baseaddr + 0xCC371E0;
var metadataRegistration = baseaddr + 0xF4EF330;
```

**to**

```
var codeRegistration = baseaddr + 0x95E17F0;
var metadataRegistration = baseaddr + 0xA747FA0;
```

**Replace code in MetaData.cs**

`stringLiterals = ReadMetadataClassArray<Il2CppStringLiteral>(0x25611C, (int)header.genericContainersOffset - 0x25611C);`

**to**

`stringLiterals = ReadMetadataClassArray<Il2CppStringLiteral>(0xDE220, (int)header.genericContainersOffset - 0xDE220);`

and this part

`result = LookupNameTranslation(ReadStringToNull(0xE63A28 + index));`

**to**

`result = LookupNameTranslation(ReadStringToNull(0xCF1124 + index));`

You can get client - [here](https://autopatchhk.yuanshen.com/client_app/pc_mihoyo/20210721_3a3ca8dfe8b26ea2/GenshinImpact_2.0.0.zip)

And decryption blob for 2.0 - [decryption_blob_2.0-rel.zip](https://github.com/khang06/Il2CppDumper-YuanShen/files/7072822/decryption_blob_2.0-rel.zip)

**Do not forget that you will need to dump global-metadata.dat from memory before use tool.**

If you did everything correct then you should get something like this
Screenshot_2

Have fun 👍 :)

**Comment by nitrog0d** [comment]
Hi Ekey, you got a Discord account? I have a few questions if you could answer, thank you

**Comment by AugustToko** [comment]
👀

**Comment by Ekey** [comment]
> Hi Ekey, you got a Discord account? I have a few questions if you could answer, thank you

Yep - Ekey#8012

**Comment by ScatteredSnow** [comment]
How to get the stringliterals value?

**Comment by gametest2025** [comment]
How are you?
Can you try to unpack the Ch
[data.lpq.zip](https://github.com/user-attachments/files/18354453/data.lpq.zip)
inese client datas.lpq file?

**Comment by khang06** [comment]
> How are you? Can you try to unpack the Ch [data.lpq.zip](https://github.com/user-attachments/files/18354453/data.lpq.zip) inese client datas.lpq file?

sorry, i have absolutely no idea what this file is. i haven't worked on anything genshin related for almost 3 years at this point

**Pull request closed without merging**
